version: '3.7'

services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGODB_USER: express
        MONGODB_PASS: express
      ports:
        - 8010:27017
